# Generated by Django 5.0.6 on 2024-05-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variations_delete_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='variation_category',
            new_name='variation_color',
        ),
        migrations.RenameField(
            model_name='variations',
            old_name='variation_value',
            new_name='variation_size',
        ),
    ]
