# Generated by Django 5.0.6 on 2024-05-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variations_created_date_variations_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='variation_color',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variations',
            old_name='variation_size',
            new_name='variation_value',
        ),
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_set', to='store.product'),
        ),
    ]
